// Generated by https://quicktype.io

export interface WeatherResponse {
  cod: string;
  message: number;
  cnt: number;
  list: Weather[];
  city: CityInfo;
  updatedAt: number;
}

export interface CityInfo {
  coord: Coordinations;
  country: string;
  id: number;
  name: string;
  population: number;
  sunrise: number;
  sunset: number;
  timezone: number;
}

export interface Coordinations {
  lat: number;
  lon: number;
}

export interface Weather {
  clouds: Clouds;
  dt: number;
  dt_txt: string;
  main: MainClass;
  pop: number;
  rain?: Rain;
  sys: Sys;
  visibility: number;
  weather: WeatherElement[];
  wind: Wind;
  updateAt?: number;
  city?: CityInfo;
  snow?: Rain;
}

export interface Clouds {
  all: number;
}

export interface MainClass {
  feels_like: number;
  grnd_level: number;
  humidity: number;
  pressure: number;
  sea_level: number;
  temp: number;
  temp_kf: number;
  temp_max: number;
  temp_min: number;
}

export interface Rain {
  "3h": number;
}

export interface Sys {
  pod: Pod;
}

export enum Pod {
  D = "d",
  N = "n",
}

export interface WeatherElement {
  description: string;
  icon: string;
  id: number;
  main: MainEnum;
}

export enum MainEnum {
  Clear = "Clear",
  Clouds = "Clouds",
  Rain = "Rain",
  Snow = "Snow",
}

export interface Wind {
  deg: number;
  gust: number;
  speed: number;
}
